language: python
python:
 - "3.8"
services:
 - mysql
test:
 - adapter: mysql2
 - database: sportsapp-test
 - username: sportsapp
 - encoding: utf8
install:
 - pip install -r requirements.txt
script:
 - nose2 -v --with-coverage tests
 - pylint --output-format=text app
 - pylint --output-format=text tests
