language: python
python:
- '3.8'
services:
- mysql
before_install:
- echo "USE mysql; CREATE USER 'sportsapp'@'localhost' IDENTIFIED BY 'sportsapp';"
  | mysql -u root
- mysql -e 'GRANT ALL PRIVILEGES ON *. * TO sportsapp@localhost;'
- mysql -e 'CREATE DATABASE sportsapp_test;'
install:
- pip install -r requirements.txt
script:
- nose2 -v --with-coverage tests
- pylint --output-format=text app
- pylint --output-format=text tests
deploy:
  provider: heroku
  api_key:
    secure: XbOcM/r4COfz4q/ITkJ3GNs3sWhnrpAI4h/z5Cuqi3dvi+/N+3VklW4mATF7TUWTBU5UDYC2q4Iwd+FN+ThpUG8KyJAcZv6XPGUm8/PEAggGwaZ+xTEM/LvUiAAcE73BC1FoB8mz98zLBBZoMcGxGlTw8tq2Fr9L+wJXLfnZzkgwW3wRf4MPksO4OjryPC2fCL6uLn5fnxCngSjKZ60wlki0yfQpfqr9P7mJPRiDJImdoPwr1xmE7vei524ok1oSRv61oHd9+W/zkKQjtIP7xS0lWNHVQtvUyhW3GV79ag3JPzi5VBgX8Xg09FyCQ8gVAIg+hugC4kojQRmsO/yH+7nHWbg/ligkjzb/wvL/15F3/nePEFRwB/3lZ4MJUJfpDPvDLOIR+qIDrSO6rXDEk7JM9h6FvSa9ePj5z8HHqVKvwpoVPD9WxBkNPVg6m1NQwwxBOIXo00dROtEk1ay1p6y1oJkQiAePY4hvbGf7M05DnnJAuNCXZMlwkO3s1lXkeJZvpsYiRfJiYtacJhlP7zOwAcVPj1xs23TJ7daC6up//q6tjmJEQvnwFritJmA3RtQCPW3mSKfJ2/UhNpX4RkbQLPvQR7/jiAq73m8laLD1DKIGJEVhLdslZ4I2A6evUTPEQXo1YfViK41fVTclP4/oceMc9galKkt6C6csdhg=
  app: glo-2005-sportsapp
  on:
    repo: ExiledNarwal28/glo-2005-sportsapp
    branch: continousIntegration # TODO : Change for master
