language: python
python:
 - "3.8"
services:
 - mysql
before_install:
 - mysql -e "CREATE USER 'sportsapp'@'localhost' IDENTIFIED BY 'sportsapp';"
 - mysql -e "GRANT ALL PRIVILEGES ON *. * TO 'sportsapp'@'localhost';"
 - mysql -e "CREATE DATABASE 'sportsapp_test';"
install:
 - pip install -r requirements.txt
script:
 - nose2 -v --with-coverage tests
 - pylint --output-format=text app
 - pylint --output-format=text tests
