language: python
python:
 - "3.8"
services:
 - mysql
test:
 - adapter: mysql2
 - database: sportsapp_test
 - username: travis
 - encoding: utf8
before_install:
 - mysql -e 'CREATE DATABASE sportsapp_test;'
install:
 - pip install -r requirements.txt
script:
 - nose2 -v --with-coverage tests
 - pylint --output-format=text app
 - pylint --output-format=text tests
