version: '2'

services:
  web:
    restart: always
    build: web
    expose:
      - "5000"
    volumes:
      - /home/flask/app/web
    command: /usr/local/bin/gunicorn -w 2 -b :5000 project:app
    depends_on:
      - mysql

  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web

  data:
    image: mysql:8.0
    volumes:
      - /var/lib/mysql
    command: "true"

  mysql:
    restart: always
    build: mysql
    volumes_from:
      - data
    expose:
      - "5432"
