name: SportsApp CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint app
        run: pylint --output-format=text app
      - name: Lint tests
        run: pylint --output-format=text tests
      - name: Shutdown default database
        run: sudo service mysql stop
      - name: Set up test database
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'sportsapp_test'
          mysql user: 'sportsapp'
          mysql password: 'sportsapp'
      - name: Unit tests
        run: nose2 -v --with-coverage tests
