name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: sportsapp
          MYSQL_PASSWORD: sportsapp
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sportsapp_test
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint app
        run: pylint --output-format=text app
      - name: Lint tests
        run: pylint --output-format=text tests
      - name: Create test database
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "
            USE mysql;
            CREATE USER 'sportsapp'@'localhost' IDENTIFIED BY 'sportsapp';
            GRANT ALL PRIVILEGES ON *. * TO sportsapp@localhost;
            CREATE DATABASE IF NOT EXISTS sportsapp_test;"
      - name: Unit tests
        run: coverage run -m nose2 tests
      - name: Generate coverage report
        run: coverage xml
      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
