name: API Unit test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          cd backend/web
          pip install -q -r requirements.txt
          nose2 -v --with-coverage project.tests
