name: API Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests and coverage
        run: |
          pip install -q -r requirements.txt
          nose2 -v --with-coverage project.tests
        working-directory: ./backend/web
