name: SportsApp CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint app and tests
        run: |
          pylint --output-format=text app
          pylint --output-format=text tests
      - name: Set up test database
      - name: Set up Python ${{ matrix.python-version }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'sportsapp_test'
          mysql user: 'sportsapp'
          mysql password: 'sportsapp'
      - name: Unit tests
        run: nose2 -v --with-coverage tests
