name: API Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -q -r requirements.txt
        working-directory: ./backend/web
      - name: Tests and coverage
        uses: CyberZHG/github-action-python-test@0.0.1 -v --with-coverage project.tests
